spring:
  config:
    activate:
      on-profile: "prodDB"
  application:
    name: game-service

  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/webflux
    username: root
    password: ${MYSQL_PASSWORD}
    #initialization-mode: always
  data:
    mongodb:
      uri: ${MONGO_URL}
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${spring.application.name}:${server.port}
