version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: webflux
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 12345678
      TZ: Asia/Seoul
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test_network
  springbootapp:
    image: ji0513ji/game-server:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=prodDB
      - DB_PASSWORD=12345678
    networks:
      - test_network
networks:
  test_network:
